### ISSUE TITLE
Detected as virus (VirusTotal)

### ISSUE THREAD

**Issue by alexpovel** [nneonneo/universal-doom#1]
This issue has been flagged in the [original HN thread](https://news.ycombinator.com/item?id=25094220) already (see [on VirusTotal](https://www.virustotal.com/gui/file/d395f426ed2b7701c09313157297a47ce94f9d767ea089079bc36783b55374c6/detection), SHA256 `D395F426ED2B7701C09313157297A47CE94F9D767EA089079BC36783B55374C6`). You personally acknowledged it and I can live with the explanation (without knowing anything about that):

>  If I had to guess, the scanners are picking up on the fact that it’s UPX-packed with funny headers. I don’t know how much my word is worth, but I give you my word that I compiled the binary from source and there’s nothing malicious in there. You’re welcome to upx -d the binary to check this yourself, or build your own copy with the instructions in the repo if you’re in doubt :) 

However, I downloaded the Windows EXE when the thread was originally created. Now, *over a week later*, Windows Defender flagged the file and put it into quarantine, when I already forgot I had downloaded it. Of course, the initial warning of a found threat was a bit of a shock. I was dumbfounded, but finally seeing the file name cleared it up.

So I just felt like this should be documented somewhere, with a google-able hash and whatnot, for folks who suffer this nasty surprise as well.

Cheers

**Comment by highfestiva** [comment]
Same hear. But just a few days ago Windows flagged my own binary as a trojan as well. Guessing MS have increased the warning levels on non-signed binaries lately.

**Comment by nneonneo** [comment]
Hmm, maybe I could try not using UPX on the binaries. I'll spin another version without UPX on either binary and see if VirusTotal gets mad about that :)

**Comment by nneonneo** [comment]
I built the binary without UPX, and it became less suspicious: https://www.virustotal.com/gui/file/5ca97717fd79f833b248ae5985fffadbee39533f5e0529bc9d7b439e08b8f1d2/detection

Hopefully that addresses the issue. I still want to keep the original binary since it's smaller (<1MB is a nice claim to be able to keep!), but the new non-UPX binary should be less problematic.
